[broadcom-wl]
desc = 'Broadcom 802.11 Linux STA wireless driver'
class_ids = "0200 0280 0282"
vendor_ids = "14E4 14A4"
device_ids = "4311 4312 4315 4727 4328 4329 432A 432B 432C 432D 0576 4353 4357 4358 4359 4365 4331 43B1 43A0 4360"
priority = 1
packages = 'broadcom-wl-dkms linux-firmware-broadcom'
post_install = """
    cat <<EOF >/etc/modprobe.d/01-chwd-net-blacklist.conf
# Do not load modules on boot.
blacklist b43
blacklist b43legacy
blacklist ssb
blacklist bcm43xx
blacklist brcm80211
blacklist brcmfmac
blacklist brcmsmac
blacklist bcma
EOF
    mkinitcpio -P
"""
post_remove = """
    rm -f /etc/modprobe.d/01-chwd-net-blacklist.conf
    mkinitcpio -P
"""

[marvell-wifi]
desc = 'Marvell AVASTAR 802.11ac Wireless (88W8897) firmware'
class_ids = "0200 0280"
vendor_ids = "11AB"
device_ids = "*"
priority = 1
packages = 'linux-firmware-marvell'

[intel-wifi]
desc = "Intel Corporation Wi-Fi"
class_ids = "0280"
vendor_ids = "8086"
device_ids = "*"
priority = 1
packages = 'iwd'
post_install = """  
    cat <<EOF >/etc/modprobe.d/01-chwd-net-intel-wifi.conf
# This file is automatically generated by chwd. PLEASE DO NOT EDIT IT.
options iwlwifi power_save=0
options iwlmvm power_scheme=1
EOF

    mkdir -p /etc/iwd
    cat <<EOF >/etc/iwd/main.conf
# This file is automatically generated by chwd.
[DriverQuirks]
PowerSaveDisable=*
EOF

    cat <<EOF >/etc/NetworkManager/conf.d/01-chwd-net-intel-wifi.conf
# This file is automatically generated by chwd. PLEASE DO NOT EDIT IT.
[device]
wifi.backend=iwd

[connection]
wifi.powersave=2
EOF

    mkinitcpio -P
"""
post_remove = """
    rm -f /etc/modprobe.d/01-chwd-net-intel-wifi.conf
    rm -f /etc/NetworkManager/conf.d/01-chwd-net-intel-wifi.conf
    
    mkinitcpio -P
"""
